# Generated by Django 4.1.5 on 2023-01-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_grupo_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grupo',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='grupo',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='nombre',
            new_name='name',
        ),
    ]
