# Generated by Django 4.1.5 on 2023-01-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_cam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='web.group'),
        ),
    ]
