# Generated by Django 4.1.7 on 2023-02-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_cam_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(upload_to='')),
                ('items', models.CharField(max_length=100)),
                ('pred', models.CharField(max_length=100)),
                ('cam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.cam')),
            ],
        ),
    ]
