# Generated by Django 4.1.7 on 2023-02-28 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_detection_items_alter_detection_pred'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='detector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.detector'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='img',
            field=models.ImageField(upload_to='static/detections'),
        ),
    ]
