# Generated by Django 4.1.7 on 2023-04-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_detection_detector_alter_detection_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='cam',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='detector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
